# Example webserv config with 2 servers

:8080 {
    root /tmp
    max_body_sz 2048

    # Serve the main site from server's root with directory browsing
    handle / {
        file_server browse
        default_file index.html
        methods POST GET
        cgi py /usr/bin/python3
	    cgi php /usr/bin/php

    }

    # Upload endpoint
    handle /upload {
        upload_enabled /tmp
	  methods GET POST DELETE
    }

    # Legacy redirect
    handle /old {
        redirect 302 /new
        methods GET
    }

    handle /new {
        methods GET
    }

    # Images served from a different root
    handle /images {
        root /tmp
        file_server
        methods GET
    }

    handle /get {
        methods GET
    }

    handle /get/post_only {
        methods POST
        upload_enabled
        file_server browse
	    # methods GET POST DELETE
    }
}

# localhost:9090 {
#     root /tmp
#     # error_page 404 404.html
#     max_body_sz 1024

#     # Serve only under /app (no browse)
#     handle /app {
#         file_server
#         default_file index.html
#         methods GET
#     }

#     # API route (no file_server; just restrict methods as a placeholder)
#     handle /api {
#         methods GET POST DELETE
#     }

#     handle /uploads {
#         upload_enabled
#         methods POST
#     }

#     # Redirect to an external URL
#     handle /docs {
#         redirect 301 https://example.com/docs
#         methods GET
#     }
# }
